---
Gemfile:
  optional:
    ':development':
      - gem: 'github_changelog_generator'
        git: 'https://github.com/skywinder/github-changelog-generator'
        ref: '20ee04ba1234e9e83eb2ffb5056e23d641c7a018'
        condition: "Gem::Version.new(RUBY_VERSION.dup) >= Gem::Version.new('2.2.2')"
      - gem: 'puppet-strings'

Rakefile:
  requires:
    - 'puppet-strings/tasks'

spec/spec_helper.rb:
  mock_with: ':rspec'

.gitlab-ci.yml:
  delete: true

appveyor.yml:
  delete: true
  
.travis.yml:
  delete: true

.github/workflows/auto_release.yml:
  unmanaged: false

.github/workflows/release.yml:
  unmanaged: false

.github/workflows/pr_test.yml:
  unmanaged: false

.github/workflows/spec.yml:
  checks: 'syntax lint metadata_lint check:symlinks check:git_ignore check:dot_underscore check:test_file rubocop'
  unmanaged: false